export interface Tool {
  name: string;
  desc: string;
  descEn: string;
  url: string;
}

export interface ToolCategory {
  id: string;
  titleKey: string;
  tools: Tool[];
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: "common",
    titleKey: "tools.cat_common",
    tools: [
      { name: "Namebio", desc: "国际市场域名交易行情", descEn: "Historical domain sales data & market trends", url: "https://namebio.com" },
      { name: "Dotdb", desc: "域名关键字排名", descEn: "Domain keyword ranking & research tool", url: "https://dotdb.com" },
      { name: "Dnpedia", desc: "每日域名注册数据", descEn: "Daily domain registration statistics", url: "https://dnpedia.com/tlds/daily.php" },
      { name: "Dnpedia", desc: "最近注册的域名搜索", descEn: "Search recently registered domains", url: "https://dnpedia.com/tlds/search.php" },
      { name: "domainnamestat", desc: "后缀注册总量统计", descEn: "TLD registration volume statistics", url: "https://domainnamestat.com" },
      { name: "Ntldstats", desc: "新顶级注册统计", descEn: "New TLD registration statistics & analytics", url: "https://ntldstats.com" },
      { name: "Tld-list", desc: "后缀注册比价", descEn: "Compare domain registration prices across TLDs", url: "https://tld-list.com" },
      { name: "ExpiredDomains", desc: "过期域名查询", descEn: "Search expired and deleted domain names", url: "https://expireddomains.net" },
      { name: "Alter", desc: "品牌域名交易平台", descEn: "Brandable domain name marketplace", url: "https://alter.com" },
      { name: "Dnpric", desc: "域名交易价格查询", descEn: "Domain transaction price lookup tool", url: "https://dnpric.es" },
      { name: "可备案后缀", desc: "国内可备案后缀查询", descEn: "ICP-eligible TLD list for China", url: "https://beian.miit.gov.cn" },
      { name: "Deepl", desc: "高精度AI翻译工具", descEn: "High-accuracy AI-powered translation", url: "https://deepl.com" },
      { name: "玩米网", desc: "域名行情走势与交易社区", descEn: "Chinese domain market trends & trading community", url: "https://www.wanmi.cc" },
      { name: "笨米网", desc: "域名综合查询工具", descEn: "Multi-function domain research tool", url: "https://www.benmi.com" },
      { name: "Completedns", desc: "域名注册历史查询", descEn: "Domain registration history lookup", url: "https://completedns.com" },
      { name: "哪煮米", desc: "哪里煮米便宜（人工更新）", descEn: "Domain registrar price comparison (manually updated)", url: "https://www.nazhumi.com" },
      { name: "Securitytrails", desc: "域名历史主机/DNS绑定查询", descEn: "Domain DNS & hosting history lookup", url: "https://securitytrails.com" },
      { name: "Crunchbase", desc: "终端公司相关信息查询", descEn: "End-user company information & funding data", url: "https://crunchbase.com" },
      { name: "Snovio", desc: "终端联系方式查询", descEn: "Find email contacts of potential end-users", url: "https://snov.io" },
      { name: "Rocketreach", desc: "终端联系方式查询", descEn: "Contact lookup for business end-users", url: "https://rocketreach.co" },
      { name: "GGCX", desc: "域名综合信息查询", descEn: "Comprehensive domain information query", url: "https://ggcx.com" },
      { name: "Iana", desc: "域名注册局联系方式", descEn: "IANA registry contact information", url: "https://iana.org" },
      { name: "Domcomp", desc: "注册/续费/转入价格比价", descEn: "Compare domain registration, renewal & transfer prices", url: "https://domcomp.com" },
      { name: "Trademarkia", desc: "域名商标查询", descEn: "Domain trademark search & monitoring", url: "https://trademarkia.com" },
      { name: "WIPO", desc: "域名仲裁查询（国际）", descEn: "WIPO domain arbitration & UDRP cases", url: "https://www.wipo.int" },
      { name: "UDRP", desc: "域名仲裁查询（NAF）", descEn: "NAF UDRP domain dispute resolution", url: "https://www.adrforum.com/domains" },
      { name: "WHTOP", desc: "国别域名注册商查询", descEn: "Country-code domain registrar directory", url: "https://www.whtop.com" },
      { name: "Domainhacks", desc: "域名Hacks创意查询", descEn: "Creative domain hacks finder by keyword", url: "https://domainhacks.info" },
      { name: "Morewords", desc: "创意单词组合域名挖掘", descEn: "Creative word combination for domain brainstorming", url: "https://www.morewords.com" },
      { name: "Hunter", desc: "查看终端公司的联系方式", descEn: "Find email addresses of end-user companies", url: "https://hunter.io" },
      { name: "Archive", desc: "查询域名的历史建站记录", descEn: "Wayback Machine — domain website history", url: "https://web.archive.org" },
      { name: "DomainR", desc: "域名可用性实时查询", descEn: "Real-time domain availability & search", url: "https://domainr.com" },
      { name: "Domainbasics", desc: "域名基础知识科普", descEn: "Domain name fundamentals & education", url: "https://basics.domains" },
      { name: "Domainleads", desc: "智能匹配域名与终端", descEn: "Match domain names with end-user leads", url: "https://domainleads.io" },
      { name: "Oneword", desc: "推荐可注册的优质单词域名", descEn: "Discover quality single-word available domains", url: "https://oneword.domains" },
      { name: "Estibot", desc: "域名价值自动估算工具", descEn: "Automated domain appraisal & valuation", url: "https://estibot.com" },
      { name: "Namelix", desc: "AI驱动的域名品牌命名", descEn: "AI-powered brand name & domain generator", url: "https://namelix.com" },
      { name: "Lean Domain Search", desc: "批量组合词域名搜索", descEn: "Bulk domain name search with word combinations", url: "https://leandomainsearch.com" },
      { name: "Bust A Name", desc: "多词组合域名创意工具", descEn: "Multi-word domain name brainstorming tool", url: "https://www.bustaname.com" },
      { name: "Wordoid", desc: "创意拼接词域名生成", descEn: "Creative made-up word domain generator", url: "https://wordoid.com" },
      { name: "Panabee", desc: "域名与APP名称创意查询", descEn: "Domain & app name idea generator", url: "https://panabee.com" },
      { name: "ICANN WHOIS", desc: "ICANN官方WHOIS查询", descEn: "ICANN official WHOIS lookup service", url: "https://lookup.icann.org" },
      { name: "Spamhaus", desc: "域名垃圾邮件/黑名单查询", descEn: "Domain spam & blacklist check", url: "https://www.spamhaus.org" },
      { name: "IPinfo", desc: "IP地址与归属查询", descEn: "IP address geolocation & ownership lookup", url: "https://ipinfo.io" },
    ],
  },
  {
    id: "parking",
    titleKey: "tools.cat_parking",
    tools: [
      { name: "Dan", desc: "国际主流域名停放销售平台", descEn: "Popular international domain marketplace & parking", url: "https://dan.com" },
      { name: "Sedo", desc: "全球最大域名停放销售平台", descEn: "World's largest domain parking & sales platform", url: "https://sedo.com" },
      { name: "4.cn", desc: "国内主流域名停放销售平台", descEn: "Leading Chinese domain parking & trading platform", url: "https://www.4.cn" },
      { name: "Flippa", desc: "域名及网站停放销售平台", descEn: "Marketplace for domains, websites & digital assets", url: "https://flippa.com" },
      { name: "Bodis", desc: "域名停放收益变现平台", descEn: "Domain parking platform with revenue monetization", url: "https://bodis.com" },
      { name: "Escrow", desc: "国际域名交易资金托管服务", descEn: "Secure domain transaction escrow service", url: "https://escrow.com" },
      { name: "Parklogic", desc: "智能优化域名停放收益", descEn: "Intelligent domain parking revenue optimization", url: "https://parklogic.com" },
      { name: "Parkingcrew", desc: "专业域名停放变现平台", descEn: "Professional domain parking & monetization", url: "https://parkingcrew.net" },
      { name: "Afternic", desc: "GoDaddy旗下域名挂牌销售", descEn: "GoDaddy's premium domain listing & brokerage", url: "https://afternic.com" },
      { name: "Efty", desc: "专业域名投资组合管理", descEn: "Professional domain portfolio management platform", url: "https://efty.com" },
      { name: "Above", desc: "高端域名停放与变现", descEn: "Premium domain parking & monetization platform", url: "https://above.com" },
      { name: "HugeDomains", desc: "大量优质域名直接销售", descEn: "Large inventory of premium domains for direct sale", url: "https://hugedomains.com" },
      { name: "BrandBucket", desc: "品牌创业域名交易市场", descEn: "Curated brandable domain names for startups", url: "https://brandbucket.com" },
      { name: "Voodoo", desc: "域名停放收益优化平台", descEn: "Domain parking with yield optimization", url: "https://voodoo.com" },
    ],
  },
  {
    id: "backorder",
    titleKey: "tools.cat_backorder",
    tools: [
      { name: "Hexonet", desc: "德国知名新后缀域名抢注商", descEn: "German registrar known for new TLD backorders", url: "https://hexonet.net" },
      { name: "西部数码", desc: "国内米农常用注册交易抢注平台", descEn: "Popular Chinese registrar for domain trading & backorders", url: "https://www.west.cn" },
      { name: "中资源", desc: "国内抢注新后缀域名成功率高", descEn: "High success rate for new TLD backorders in China", url: "https://www.zzy.cn" },
      { name: "Catched", desc: "无需充值即可抢注域名", descEn: "No prepayment required for domain backordering", url: "https://catched.com" },
      { name: "Dynadot", desc: "知名域名抢注服务商", descEn: "Well-known registrar with reliable backorder service", url: "https://dynadot.com" },
      { name: "Sav", desc: "新后缀注册价格低廉的抢注商", descEn: "Affordable new TLD backorder registrar", url: "https://sav.com" },
      { name: "Rrpproxy", desc: "无需竞价的域名抢注服务", descEn: "Domain backorder service without bidding required", url: "https://rrpproxy.net" },
      { name: "Istanco", desc: ".ax .rs 域名抢注先到先得", descEn: "First-come-first-served .ax .rs domain backorder", url: "https://istanco.net" },
      { name: "Park.io", desc: "抢注国别域名实力较强", descEn: "Strong ccTLD domain backorder capabilities", url: "https://www.park.io" },
      { name: "聚名网", desc: "国内知名主流后缀域名抢注商", descEn: "Well-known Chinese backorder service for mainstream TLDs", url: "https://www.juming.com" },
      { name: "Nicsell", desc: ".de .li .se .eu 域名抢注", descEn: "European ccTLD backorder service", url: "https://nicsell.com" },
      { name: "AI注册局", desc: ".ai域名抢注注册商", descEn: ".ai domain backorder registrar", url: "https://nic.ai" },
      { name: "Catch.club", desc: "域名抢注综合服务商", descEn: "Comprehensive domain backorder & auction service", url: "https://catch.club" },
      { name: "Snapnames", desc: "国际知名主流后缀域名抢注商", descEn: "International leader in mainstream TLD backorders", url: "https://snapnames.com" },
      { name: "Namejet", desc: "国际知名主流后缀域名抢注商", descEn: "Major international domain backorder & auction platform", url: "https://namejet.com" },
      { name: "Dropcatch", desc: "国际知名主流后缀域名抢注商", descEn: "Well-known platform for catching dropped domains", url: "https://dropcatch.com" },
      { name: "EE注册局", desc: ".ee爱沙尼亚域名抢注", descEn: ".ee Estonia domain backorder service", url: "https://www.internet.ee" },
      { name: "RU注册局", desc: ".ru俄罗斯域名抢注", descEn: ".ru Russia domain backorder service", url: "https://nic.ru" },
      { name: "Expireddomains", desc: ".nz新西兰域名抢注", descEn: ".nz New Zealand expired domain backorder", url: "https://www.expireddomains.net" },
      { name: "Rymdweb", desc: ".se .nu域名抢注服务", descEn: ".se .nu Scandinavian domain backorder service", url: "https://www.rymdweb.com" },
      { name: "Nidoma", desc: ".it意大利域名抢注", descEn: ".it Italy domain backorder service", url: "https://nidoma.com" },
      { name: "Catchtiger", desc: ".li列支敦士登域名抢注", descEn: ".li Liechtenstein domain backorder", url: "https://www.catchtiger.com" },
      { name: "Namecase", desc: ".it意大利域名抢注服务", descEn: ".it Italy domain backorder & registration", url: "https://namecase.com" },
    ],
  },
  {
    id: "news",
    titleKey: "tools.cat_news",
    tools: [
      { name: "Dnjournal", desc: "域名行业权威资讯与交易新闻", descEn: "Authority domain industry news & sales reports", url: "https://dnjournal.com" },
      { name: "Domaingang", desc: "域名行业资讯与交易新闻", descEn: "Domain industry news & market commentary", url: "https://domaingang.com" },
      { name: "Techcrunch", desc: "高科技终端融资新闻", descEn: "Tech startup & funding news for end-user research", url: "https://techcrunch.com" },
      { name: "Techstars", desc: "全球知名创业孵化器融资动态", descEn: "Global startup accelerator portfolio & funding news", url: "https://techstars.com" },
      { name: "500 Startups", desc: "高科技终端融资新闻", descEn: "Startup investment & accelerator news", url: "https://500.co" },
      { name: "Domainnamewire", desc: "域名行业资讯与新闻", descEn: "Domain name industry news & analysis", url: "https://domainnamewire.com" },
      { name: "Domaining", desc: "域名投资综合资讯平台", descEn: "Domain investing news & community", url: "https://www.domaining.com" },
      { name: "TheDomainscom", desc: "域名行业热点与资讯", descEn: "Domain industry news, trends & transactions", url: "https://thedomains.com" },
      { name: "Domain Sherpa", desc: "域名访谈与教育视频节目", descEn: "Domain investing interviews, podcasts & education", url: "https://domainsherpa.com" },
      { name: "CircleID", desc: "互联网治理与域名行业深度文章", descEn: "Internet governance & domain industry in-depth articles", url: "https://circleid.com" },
      { name: "Domain Incite", desc: "域名行业专业新闻", descEn: "Professional domain industry news & analysis", url: "https://domainincite.com" },
      { name: "Domainstate", desc: "域名销售数据与行业动态", descEn: "Domain sales data & market dynamics", url: "https://domainstate.com" },
    ],
  },
  {
    id: "dns",
    titleKey: "tools.cat_dns",
    tools: [
      { name: "DNSPod", desc: "腾讯旗下免费智能DNS解析", descEn: "Tencent's free intelligent DNS resolution service", url: "https://www.dnspod.cn" },
      { name: "帝恩思", desc: "高防护DNS域名解析服务商", descEn: "High-security DNS resolution service provider", url: "https://www.dns.com.cn" },
      { name: "华为云DNS", desc: "华为云企业级DNS服务", descEn: "Huawei Cloud enterprise-grade DNS service", url: "https://www.huaweicloud.com/product/dns.html" },
      { name: "阿里云DNS", desc: "阿里云域名解析与管理", descEn: "Alibaba Cloud domain DNS management", url: "https://wanwang.aliyun.com/domain/dns" },
      { name: "DNS.LA", desc: "免费智能DNS解析平台", descEn: "Free intelligent DNS resolution platform", url: "https://www.dns.la" },
      { name: "ZoneEdit", desc: "美国老牌免费域名DNS解析", descEn: "Veteran US free domain DNS resolution service", url: "https://www.zoneedit.com" },
      { name: "HE.NET", desc: "美国老牌IDC与DNS服务", descEn: "Hurricane Electric — veteran US IDC & DNS service", url: "https://dns.he.net" },
      { name: "FreeDNS", desc: "老牌免费DNS解析平台", descEn: "Long-running free DNS resolution platform", url: "https://freedns.afraid.org" },
      { name: "Cloudflare", desc: "全球CDN与免费DNS服务", descEn: "Global CDN & free enterprise-grade DNS service", url: "https://cloudflare.com" },
      { name: "ClouDNS", desc: "国际知名DNS解析服务", descEn: "International DNS hosting & management service", url: "https://www.cloudns.net" },
      { name: "AWS Route53", desc: "亚马逊云高可用DNS服务", descEn: "Amazon Web Services scalable cloud DNS service", url: "https://aws.amazon.com/route53" },
      { name: "Google Cloud DNS", desc: "谷歌云高性能DNS服务", descEn: "Google Cloud high-performance DNS service", url: "https://cloud.google.com/dns" },
      { name: "NS1", desc: "高级流量路由智能DNS", descEn: "Advanced traffic routing & intelligent DNS", url: "https://ns1.com" },
      { name: "Constellix", desc: "企业级智能DNS管理", descEn: "Enterprise-grade intelligent DNS management", url: "https://constellix.com" },
      { name: "Gcore DNS", desc: "全球边缘节点DNS解析", descEn: "Global edge network DNS resolution", url: "https://gcore.com/dns" },
      { name: "Bunny DNS", desc: "高速全球CDN与DNS服务", descEn: "Fast global CDN with integrated DNS management", url: "https://bunny.net" },
    ],
  },
  {
    id: "registrar",
    titleKey: "tools.cat_registrar",
    tools: [
      { name: "阿里云", desc: "国内终端最喜欢的域名注册交易平台", descEn: "China's most popular domain registration & trading platform", url: "https://wanwang.aliyun.com" },
      { name: "中资源", desc: "国内注册量大、新后缀成功率高", descEn: "High-volume Chinese registrar with strong new TLD support", url: "https://www.zzy.cn" },
      { name: "Porkbun", desc: "全球米农公认的便宜注册商", descEn: "Globally recognized affordable domain registrar", url: "https://porkbun.com" },
      { name: "Dynadot", desc: "受欢迎的国外域名注册商", descEn: "Popular international domain registrar", url: "https://dynadot.com" },
      { name: "Hexonet", desc: "德国著名域名注册商", descEn: "Well-known German domain registrar", url: "https://hexonet.net" },
      { name: "趣域网", desc: "国内最全国别域名注册商", descEn: "Most comprehensive ccTLD registrar in China", url: "https://www.quyu.net" },
      { name: "网维互联", desc: "国内国别域名注册较全", descEn: "Diverse ccTLD registration in China", url: "https://www.wvidc.com" },
      { name: "易名网", desc: "国内知名主流后缀注册商", descEn: "Well-known Chinese registrar for mainstream TLDs", url: "https://www.ename.net" },
      { name: "腾讯云", desc: "国内优惠券最多的注册商", descEn: "Tencent Cloud — most coupons & deals for domain registration", url: "https://cloud.tencent.com/product/domain" },
      { name: "Godaddy", desc: "历史悠久的全球知名注册商", descEn: "World's largest and most recognized domain registrar", url: "https://godaddy.com" },
      { name: "Afriregister", desc: "非洲国家后缀专业注册商", descEn: "Specialist in African ccTLD registrations", url: "https://www.afriregister.com" },
      { name: "101domain", desc: "支持全球最多后缀的注册商", descEn: "Widest TLD support globally — most domain extensions", url: "https://www.101domain.com" },
      { name: "Netim", desc: "支持域名后缀数量极多的注册商", descEn: "Extensive TLD portfolio registrar", url: "https://www.netim.com" },
      { name: "Sav", desc: "新后缀注册价格较低的注册商", descEn: "Competitive pricing for new TLD registrations", url: "https://sav.com" },
      { name: "Namesilo", desc: "支持支付宝的国外知名注册商", descEn: "Affordable registrar supporting Alipay payments", url: "https://namesilo.com" },
      { name: "Namecheap", desc: "国际知名服务优秀的注册商", descEn: "International registrar known for great service & prices", url: "https://namecheap.com" },
      { name: "Name.com", desc: "国际知名老牌注册商", descEn: "Established international domain registrar", url: "https://www.name.com" },
      { name: "Gandi", desc: "法国知名隐私友好注册商", descEn: "French registrar known for privacy & reliability", url: "https://gandi.net" },
      { name: "OVH", desc: "欧洲最大云与域名服务商", descEn: "Europe's largest cloud & domain hosting provider", url: "https://ovhcloud.com" },
      { name: "Hover", desc: "简洁好用的域名管理注册商", descEn: "Clean, user-friendly domain management registrar", url: "https://hover.com" },
      { name: "Epik", desc: "支持隐私保护的注册商", descEn: "Privacy-focused domain registrar", url: "https://epik.com" },
      { name: "NameBright", desc: "专业域名管理与注册平台", descEn: "Professional domain management & registration platform", url: "https://namebright.com" },
      { name: "Tucows/OpenSRS", desc: "域名批发与转售注册平台", descEn: "Wholesale domain reseller & registration platform", url: "https://opensrs.com" },
    ],
  },
];
