export interface Tool {
  name: string;
  desc: string;
  url: string;
}

export interface ToolCategory {
  id: string;
  title: string;
  tools: Tool[];
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: "common",
    title: "常用工具",
    tools: [
      { name: "Namebio", desc: "国际市场域名交易行情", url: "https://namebio.com" },
      { name: "Dotdb", desc: "域名关键字排名", url: "https://dotdb.com" },
      { name: "Dnpedia", desc: "每日域名", url: "https://dnpedia.com/tlds/daily.php" },
      { name: "Dnpedia", desc: "最近注册的域名搜索", url: "https://dnpedia.com/tlds/search.php" },
      { name: "domainnamestat", desc: "后缀注册总量统计", url: "https://domainnamestat.com" },
      { name: "Ntldstats", desc: "新顶级注册统计", url: "https://ntldstats.com" },
      { name: "Tld-list", desc: "后缀注册比价", url: "https://tld-list.com" },
      { name: "ExpiredDomains", desc: "过期域名查询", url: "https://expireddomains.net" },
      { name: "Alter", desc: "域名销售额前500名", url: "https://alter.com" },
      { name: "Dnpric", desc: "交易价格查询", url: "https://dnpric.com" },
      { name: "可备案后缀", desc: "国内可备案后缀查询", url: "https://beian.miit.gov.cn" },
      { name: "Deepl", desc: "翻译", url: "https://deepl.com" },
      { name: "玩米网", desc: "玩米网", url: "https://www.wanmi.com" },
      { name: "笨米网", desc: "域名综合查询工具", url: "https://www.benmi.com" },
      { name: "Completedns", desc: "域名注册历史查询", url: "https://completedns.com" },
      { name: "哪煮米", desc: "哪里煮米便宜（阿姨手动更新）", url: "https://www.nazhumi.com" },
      { name: "米情局", desc: "域名注册比价（脚本更新）", url: "https://www.miqingjv.com" },
      { name: "Securitytrails", desc: "域名绑定主机历史查询", url: "https://securitytrails.com" },
      { name: "Crunchbase", desc: "终端相关信息查询", url: "https://crunchbase.com" },
      { name: "Snovio", desc: "终端联系方式查询", url: "https://snov.io" },
      { name: "Rocketreach", desc: "终端联系方式查询", url: "https://rocketreach.co" },
      { name: "GGCX", desc: "域名综合信息查询", url: "https://ggcx.com" },
      { name: "Iana", desc: "域名注册局联系方式", url: "https://iana.org" },
      { name: "Domcomp", desc: "注册续费转入价格比价", url: "https://domcomp.com" },
      { name: "Trademarkia", desc: "域名商标查询", url: "https://trademarkia.com" },
      { name: "WIPO", desc: "域名仲裁查询", url: "https://www.wipo.int" },
      { name: "UDRP", desc: "域名仲裁查询", url: "https://www.adrforum.com/domains" },
      { name: "WHTOP", desc: "国别域名注册商查询", url: "https://www.whtop.com" },
      { name: "Domainhacks", desc: "hacks查询", url: "https://domainhacks.info" },
      { name: "Morewords", desc: "创意单词组合域名挖掘", url: "https://www.morewords.com" },
      { name: "Hunter", desc: "查看终端的联系方式", url: "https://hunter.io" },
      { name: "Archive", desc: "查询域名的建站历史", url: "https://web.archive.org" },
      { name: "DomainR", desc: "域名注册信息查询", url: "https://domainr.com" },
      { name: "Domainbasics", desc: "域名基础知识", url: "https://domainbasics.com" },
      { name: "Domainleads", desc: "域名匹配终端", url: "https://domainleads.io" },
      { name: "Oneword", desc: "推荐可注册的好域名", url: "https://oneword.domains" },
    ],
  },
  {
    id: "parking",
    title: "域名停放",
    tools: [
      { name: "Dan", desc: "国际域名停放销售平台", url: "https://dan.com" },
      { name: "Sedo", desc: "国际域名停放销售平台", url: "https://sedo.com" },
      { name: "4.cn", desc: "国内域名停放销售平台", url: "https://www.4.cn" },
      { name: "Flippa", desc: "国际域名停放销售平台", url: "https://flippa.com" },
      { name: "Bodis", desc: "国际域名停放销售平台", url: "https://bodis.com" },
      { name: "Escrow", desc: "国际域名停放销售平台", url: "https://escrow.com" },
      { name: "Parklogic", desc: "国际域名停放销售平台", url: "https://parklogic.com" },
      { name: "Parkingcrew", desc: "国际域名停放销售平台", url: "https://parkingcrew.com" },
      { name: "Afternic", desc: "国际域名停放销售平台", url: "https://afternic.com" },
      { name: "Efty", desc: "国际域名停放销售平台", url: "https://efty.com" },
    ],
  },
  {
    id: "backorder",
    title: "域名抢注平台",
    tools: [
      { name: "Hexonet", desc: "德国知名新后缀域名抢注商", url: "https://hexonet.net" },
      { name: "西部数码", desc: "国内米农喜欢的注册交易抢注平台", url: "https://www.west.cn" },
      { name: "中资源", desc: "国内抢注新后缀域名成功率高", url: "https://www.zzy.cn" },
      { name: "Catched", desc: "无需充值就可以抢注域名的注册商", url: "https://catched.com" },
      { name: "Dynadot", desc: "知名域名抢注服务商", url: "https://dynadot.com" },
      { name: "Sav", desc: "新后缀注册价格比较便宜的注册商", url: "https://sav.com" },
      { name: "Rrpproxy", desc: "无需竞价的域名抢注服务", url: "https://rrpproxy.net" },
      { name: "Istanco", desc: ".ax .rs 域名抢注先到先得", url: "https://istanco.com" },
      { name: "Park", desc: "抢注国别域名比较厉害的注册商", url: "https://www.park.io" },
      { name: "聚名网", desc: "国内知名主流后缀域名抢注商", url: "https://www.juming.com" },
      { name: "Nicsell", desc: ".de .li .se .eu 域名抢注服务", url: "https://nicsell.com" },
      { name: "AI注册局", desc: "ai后缀域名抢注商", url: "https://nic.ai" },
      { name: "CatchClub", desc: "域名抢注服务商", url: "https://catchclub.com" },
      { name: "Snapnames", desc: "国际知名主流后缀域名抢注商", url: "https://snapnames.com" },
      { name: "Namejet", desc: "国际知名主流后缀域名抢注商", url: "https://namejet.com" },
      { name: "Dropcatch", desc: "国际知名主流后缀域名抢注商", url: "https://dropcatch.com" },
      { name: "EE注册局", desc: ".ee后缀域名抢注商", url: "https://www.internet.ee" },
      { name: "RU注册局", desc: ".ru后缀域名抢注商", url: "https://nic.ru" },
      { name: "Expireddomains", desc: ".nz后缀域名抢注商", url: "https://www.expireddomains.net" },
      { name: "Rymdweb", desc: ".se .nu后缀域名抢注商", url: "https://rymdweb.com" },
      { name: "Nidoma", desc: ".it后缀域名抢注商", url: "https://nidoma.com" },
      { name: "Catchtiger", desc: ".li后缀域名抢注商", url: "https://catchtiger.com" },
      { name: "Namecase", desc: ".it后缀域名抢注商", url: "https://namecase.com" },
    ],
  },
  {
    id: "news",
    title: "域名资讯平台",
    tools: [
      { name: "Dnjournal", desc: "域名行业资讯以及交易新闻", url: "https://dnjournal.com" },
      { name: "Domaingang", desc: "域名行业资讯以及交易新闻", url: "https://domaingang.com" },
      { name: "Techcrunch", desc: "高科技终端融资新闻", url: "https://techcrunch.com" },
      { name: "Techstars", desc: "高科技终端融资新闻", url: "https://techstars.com" },
      { name: "500", desc: "高科技终端融资新闻", url: "https://500.co" },
      { name: "Domainnamewire", desc: "域名行业资讯以及交易新闻", url: "https://domainnamewire.com" },
      { name: "Domaining", desc: "域名行业资讯", url: "https://www.domaining.com" },
    ],
  },
  {
    id: "dns",
    title: "域名解析",
    tools: [
      { name: "DNSPod", desc: "免费智能DNS解析服务", url: "https://www.dnspod.cn" },
      { name: "帝恩思", desc: "高防DNS域名解析服务商", url: "https://www.dns.com.cn" },
      { name: "华为云DNS", desc: "华为云DNS", url: "https://www.huaweicloud.com/product/dns.html" },
      { name: "阿里云DNS", desc: "阿里云DNS", url: "https://wanwang.aliyun.com/domain/dns" },
      { name: "DNS.LA", desc: "免费智能DNS的解析", url: "https://www.dns.la" },
      { name: "ZoneEdit", desc: "美国著名的老牌免费域名DNS解析服务", url: "https://www.zoneedit.com" },
      { name: "HE.NET", desc: "美国老牌IDC", url: "https://dns.he.net" },
      { name: "FreeDNS", desc: "美国的老牌DNS网站", url: "https://freedns.afraid.org" },
      { name: "Cloudflare", desc: "强大的国外免费CDN和DNS服务", url: "https://cloudflare.com" },
      { name: "ClouDNS", desc: "国际知名DNS解析服务", url: "https://www.coudns.net" },
    ],
  },
  {
    id: "registrar",
    title: "域名注册平台",
    tools: [
      { name: "阿里云", desc: "国内终端最喜欢的域名注册+交易平台", url: "https://wanwang.aliyun.com" },
      { name: "中资源", desc: "国内抢注新后缀域名成功率高", url: "https://www.zzy.cn" },
      { name: "Porkbun", desc: "全球米农公认的便宜注册商", url: "https://porkbun.com" },
      { name: "Dynadot", desc: "很受欢迎的国外域名注册商", url: "https://dynadot.com" },
      { name: "Hexonet", desc: "德国著名域名注册商", url: "https://hexonet.net" },
      { name: "趣域网", desc: "国内最全国别域名注册商", url: "https://www.quyuwang.com" },
      { name: "网维互联", desc: "国内国别较全域名注册商", url: "https://www.wwhl.net" },
      { name: "易名网", desc: "国内知名主流后缀域名注册商", url: "https://www.ename.com" },
      { name: "腾讯云", desc: "国内优惠券最多的域名注册商", url: "https://cloud.tencent.com/product/domain" },
      { name: "Godaddy", desc: "历史悠久全球知名的域名注册商", url: "https://godaddy.com" },
      { name: "Afriregister", desc: "比较大的非洲国家后缀注册商", url: "https://www.afriregister.com" },
      { name: "101domain", desc: "全世界支持域名后缀最多的注册商", url: "https://www.101domain.com" },
      { name: "Netim", desc: "全世界支持域名后缀最多的注册商", url: "https://www.netim.com" },
      { name: "Sav", desc: "新后缀注册价格比较便宜的注册商", url: "https://sav.com" },
      { name: "Namesilo", desc: "支持支付宝的国外知名域名注册商", url: "https://namesilo.com" },
      { name: "Namecheap", desc: "国际知名服务优秀的域名注册商", url: "https://namecheap.com" },
      { name: "Uniregistry", desc: "方便批量查询新后缀域名的注册商", url: "https://uniregistry.com" },
      { name: "Name.com", desc: "国际知名老牌注册商", url: "https://www.name.com" },
    ],
  },
];
